fc2/fc2/fc2/urls.py
from django.contrib import admin
from django.urls import path
from fcuser.views import RegisterView, index, LoginView, logout
from product.views import ProductDetail, ProductList, ProductCreate, ProductListAPI, ProductDetailAPI
from order.views import OrderCreate, OrderList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('loout/', logout),
    path('product/', ProductList.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('product/<int:pk>/', ProductDetail.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('order/', OrderList.as_view()),

    path('api/product/', ProductListAPI.as_view()),
    path('api/product/<int:pk>', ProductDetailAPI.as_view()),
]

fc2/fc2/product/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품설명')
    stock = models.IntegerField(verbose_name='재고')
    register_date = models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        verbose_name = '상품'
        verbose_name_plural = '상품'

fc2/fc2/product/forms.py
from django import forms
from .models import Product

class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required':'상품명을 입력해주세요.'
        },
        max_length=64, label='상품명'
    )
    
    price = forms.IntegerField(
        error_messages={
            'required':'상품가격을 입력해주세요.'
        }, label='상품가격'
    )
    
    description = forms.CharField(
        error_messages={
            'required':'상품설명을 입력해주세요.'
        }, label='상품설명'
    )

    stock = forms.IntegerField(
        error_messages={
            'required':'수량을 입력해주세요.'
        }, label='상품수량'
    )
    
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        stock = cleaned_data.get('stock')

        if not (name and price and description and stock):
            self.add_error('name', '값이 없습니다')
            self.add_error('price', '값이 없습니다')

fc2/fc2/order/views.py
from re import template
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from fcuser.decorators import login_required
from .forms import RegisterForm
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .models import Order
from django.db import transaction
from product.models import Product
from fcuser.models import Fcuser
# Create your views here.

@method_decorator(login_required, name='dispatch')
class OrderCreate(FormView):
    form_class = RegisterForm
    success_url = '/product/'
    
    def form_valid(self, form):
        with transaction.atomic():
            prod = Product.objects.get(pk=form.data.get('product'))
            order = Order(
                quantity = form.data.get('quantity'),
                product = prod,
                fcuser = Fcuser.objects.get(email=self.request.session.get('user')),
            )
            order.save()
            prod.stock -= int(form.data.get('quantity'))
            prod.save()

        return super().form_valid(form)

    def form_invalid(self, form):                                      
        return redirect('/product/' + str(form.data.get('product')))

    def get_form_kwargs(self, **kwargs):
        kw = super().get_form_kwargs(**kwargs)
        kw.update({
            'request': self.request
        })
        return kw
@method_decorator(login_required, name='dispatch')
class OrderList(ListView):
    template_name = 'order.html'
    context_object_name = 'order_list'

    def get_queryset(self, **kwargs):
        queryset = Order.objects.filter(fcuser__email=self.request.session.get('user'))
        return queryset

fc2/fc2/product/views.py
from django import contrib
from django.forms.forms import Form
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from fcuser.decorators import admin_required
from order.forms import RegisterForm as OrderForm
from .forms import RegisterForm
from .models import Product
from rest_framework import generics
from rest_framework import mixins
from .serializers import ProductSerializer

# Create your views here.

class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)


class ProductList(ListView):
    model = Product
    template_name = 'product.html'
    context_object_name = 'product_list'

@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stock=form.data.get('stock')
        )
        product.save()
        
        return super().form_valid(form)

class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderForm(self.request)
        return context

fc2/fc2/product/templates/product.html
{% extends "base.html" %}
{% load humanize %}
{% block header %}
<script>
    function product_detail(id) {
        $.ajax({
            url: "/api/product/" + id,
            success: function (result) {
                $("#product-" + id).popover({
                    html: true,
                    content : result.name + "<br/>" + result.price
                }).popover('show');
            }
        });
    }

    function product_leave(id) {
        $("#product-" + id).popover('hide');
    }

    $(document).ready(function () {});
</script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">상품명</th>
                    <th scope="col">가격</th>
                    <th scope="col">등록날짜</th>
                </tr>
            </thead>
            <tbody class="text-dark">
                {% for product in product_list %}
                <tr>
                    <th>{{ product.id }}</th>
                    <th><a id="product-{{ product.id }}" onmouseenter="product_detail({{ product.id }});" onmouseleave="product_leave({{ product.id }});" href="/product/{{ product.id }}">{{ product.name }}</a></th>
                    <th>{{ product.price|intcomma }}원</th>
                    <th>{{ product.register_date|date:'Y-m-d H:i' }}</th>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

fc2/fc2/product/templates/product_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12">
        <dic class="card" style="width: 100%;">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <form method="POST" action="/order/create/">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {% if field.name != 'product' %}
                            <div class="mt-2">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            </div>
                            {% endif %}
                            <div class="mt-1">    
                            {% if field.name == 'quantity' %}
                                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                                placeholder="{{ field.label }}" name="{{ field.name }}" />
                            {% elif field.name == 'product' %}
                                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
                                placeholder="{{ field.label }}" name="{{ field.name }}" value="{{product.id}}"/>
                            {% endif %}
                            </div>
                        </div>
                        {% if field.errors %}
                        <span style="color: red">{{ field.errors }}</span>
                        {% endif %}
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">주문하기</button>
                    </form>
                </li>
                <li class="list-group-item">가격: {{ product.price|intcomma }} 원</li>
                <li class="list-group-item">등록날짜: {{ product.register_date|date:'Y-m-d H:i' }}</li>
                <li class="list-group-item">설명: {{ product.description|safe }}</li>
                <li class="list-group-item">재고: {{ product.stock|intcomma }} 개</li>
            </ul>
        </dic>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <button class="favorite styled" type="button">
            <a href="/product/">목록</a>
        </button>
    </div>
</div>
<div class="row mt-5">
</div>
{% endblock %}

fc2/fc2/product/templates/register_product.html
{% extends 'base.html' %}
{% block header %}
<meta charset="UTF-8">

<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_description').summernote();
    });
    </script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12 text-center">
        <h1>상품등록</h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<div class="row mt-5">
    <div class="col-12">
        <form method="POST" action=".">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.name == 'description' %}
                <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
                {% else %}
                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.if_for_label }}"
                placeholder="{{ field.label }}" name="{{ field.name }}" />
                {% endif %}
            </div>
            {% if field.errors %}
            <span style="color: red">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <div class="col-12">
                {{ error }}
            </div>
            <button type="submit" class="btn btn-primary">등록</button>
        </form>
    </div>
</div>
{% endblock %}